include:
  - board: nice_nano@2.0.0
    shield: castor_left
    snippet: zmk-usb-logging
  - board: nice_nano@2.0.0
    shield: castor_right
    snippet: zmk-usb-logging
  - board: nice_nano@2.0.0
    shield: settings_reset