include:
  - board: nice_nano_v2
    shield: castor_left
    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: castor_right
    # snippet: zmk-usb-logging
  - board: nice_nano_v2
    shield: settings_reset